# example profiles.yml file
jaffle_shop:
  target: dev
  outputs:
    dev:
      type: postgres
      host: 127.0.0.0
      user: postgres
      password: postgres
      port: 5432
      dbname: RichSensor
      schema: dbt_alice
      threads: 4